dofile(minetest.get_modpath("bbq").."/cooking.lua")
dofile(minetest.get_modpath("bbq").."/crafts.lua")
dofile(minetest.get_modpath("bbq").."/kettle.lua")
dofile(minetest.get_modpath("bbq").."/propane_grill.lua")
dofile(minetest.get_modpath("bbq").."/propane_grill_pro.lua")
dofile(minetest.get_modpath("bbq").."/smoker.lua")
dofile(minetest.get_modpath("bbq").."/overrides.lua")
dofile(minetest.get_modpath("bbq").."/woodpile.lua")
