dofile(minetest.get_modpath("bbq").."/cooking.lua")
dofile(minetest.get_modpath("bbq").."/crafts.lua")
dofile(minetest.get_modpath("bbq").."/smoker.lua")
dofile(minetest.get_modpath("bbq").."/overrides.lua")
dofile(minetest.get_modpath("bbq").."/woodpile.lua")
